#!/usr/bin/perl
use strict;
use warnings;
use CGI;      # Модуль для работы с формами и HTML
use DBI;

# --- Настройки DB (должны быть вашими) ---
my $dsn  = "DBI:mysql:database=test_db;host=localhost";
my $user = "root";
my $pass = "secret";
# ----------------------------------------

my $q = CGI->new; # Создаем новый объект CGI

print $q->header; # Вывод HTTP-заголовка

# Проверяем, был ли запрос уже отправлен (проверяем наличие параметра 'search_button')
if ( $q->param('search_button') ) {
    
    ## 1. ОБРАБОТКА ФОРМЫ И ЗАПРОС К БД

    # Получаем значение из поля ввода
    my $search_value = $q->param('search_input');

    print $q->h2("Результаты поиска для: $search_value");

    # Выполняем запрос
    my $dbh = DBI->connect($dsn, $user, $pass, { RaiseError => 1, PrintError => 0 });
    
    # !!! БЕЗОПАСНО: Используем плейсхолдер (?) для переменной
    my $sql = "SELECT name, email FROM users WHERE name = ?"; 
    my $sth = $dbh->prepare($sql);
    
    # Передаем переменную в execute для безопасной подстановки
    $sth->execute($search_value);

    # Вывод данных
    print $q->start_ul;
    while (my $row = $sth->fetchrow_hashref) {
        print $q->li("Имя: $row->{name}, Email: $row->{email}");
    }
    print $q->end_ul;

    $sth->finish;
    $dbh->disconnect;

    print $q->p( $q->a({-href => $q->url}, "Новый поиск") );

} else {

    ## 2. ВЫВОД ФОРМЫ

    print $q->h1("Поиск пользователя по имени");
    
    # Начинаем HTML-форму
    print $q->start_form;

    # Поле ввода (имя: 'search_input')
    print $q->p("Введите имя:");
    print $q->p( $q->textfield(-name => 'search_input', -default => '', -size => 40) );
    
    # Кнопка (имя: 'search_button')
    print $q->p( $q->submit(-name => 'search_button', -value => 'Найти') );
    
    # Завершаем HTML-форму
    print $q->end_form;
}

print $q->end_html;
